# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot", "ADobin"]

[merge]
automerge_label = "ship it!"
method = "squash"

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
usernames = ["dependabot"]
versions = ["minor", "patch"]

# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
[update]
autoupdate_label = "update me please!"
ignored_usernames = ["dependabot"]
